language: cpp

install:
  - pip install --user q conan
  - conan user

script:
  - mkdir build && cd build
  - conan install -s compiler.libcxx=libstdc++11 .. --build
  - cmake .. -DCMAKE_BUILD_TYPE=Release && cmake --build .
  - ./bin/test_hello