language: cpp

install:
  - pip install --user q conan
  - conan user

script:
  - mkdir build && cd build
  - conan install .. --build=missing
  - cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --config Release
  - ./bin/test_hello