language: cpp

install:
  - pip install --user q conan
  - conan user
  - conan profile update settings.compiler.libcxx=libstdc++11 default

script:
  - mkdir build && cd build
  - conan install .. --build
  - cmake .. -DCMAKE_BUILD_TYPE=Release && cmake --build .
  - ./bin/test_hello